### PR TITLE
Updating node-gadu to work with latest nodejs and v8

### PR DESCRIPTION
**Pull request by marcin-uliasz**
Updating node-gadu to work with latest nodejs (7.3.0) and v8 (5.4.500.45). Before the update there were tons of compile errors. I did not name the commits, other than "update [filename]". You can check the commits' content. However here is a little summary:
- updated libgadu lib
- updated libuv lib
- introduced isolate
- changed the callbacks
- using Nan

43 tests are complete, after the update.

### CODE REVIEW

**Comment by marcin-uliasz** [comment]
You would have to change LIBGADU_VERSION in travis and probably add libuv

**Comment by marcin-uliasz** [comment]
Unused result warning:
bash_1

Unused private field warning:
bash_2

Tests are complete:
bash_3

**Comment by mpapierski** [comment]
Thanks for your effort! Happy to see someone using this project. And this will probably fix #2... 

Care to update travis config too? It fails because source code of libgadu moved to a new place. New location is http://github.com/wojtekka/libgadu/releases/download/1.11.2/libgadu-1.11.2.tar.gz. 

EDIT: node v0.8 in travis seems obsolete too. Since nodejs LTS is v6.9 its worth updating too.

**Comment by marcin-uliasz** [comment]
On my machine (I am using mac) node-gyp compiles the files with xcode and it works. I don't have errors, only warnings:

3__bash
3__bash

Travis uses linux and different tool chain... I don't know from where the errors comes form. Will take a look at it later again.

**Comment by mpapierski** [comment]
Looks like the problem is the gcc version. GCC 4.8 is installed, though `npm install` uses the default version which is older (I think). 

Adding

```
env:
  - CXX=g++-4.8
```

should fix the issue.

Check out this section: https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements

Thanks again your effort :)

**Comment by mpapierski** [comment]
Looks like travis is back to normal now :+1:

**Comment by marcin-uliasz** [comment]
Yes, good news. I need to only else add the libgadu version variable back (to .travis.yml), because now it is hardcoded. For test I removed it because when  I added CXX env LIBGADU env was not recognised.

**Comment by marcin-uliasz** [comment]
Looks like there is small travis issue (multiple jobs) when there are multiple env variables:

Check out this:
https://github.com/travis-ci/travis-ci/issues/287

build__23_-_mpapierski_node-gadu_-_travis_ci

**Comment by marcin-uliasz** [comment]
OK, all works now. env variables have to be in one line to not create multiple travis jobs.
If you agree with code changes I think it is ready to be merged.

**Comment by mpapierski** [comment]
Thanks!

**Pull request merged**
